services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: trellolite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ADDR: ":8080"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/trellolite?sslmode=disable"
      OAUTH_GITHUB_CLIENT_ID: "${OAUTH_GITHUB_CLIENT_ID}"
      OAUTH_GITHUB_CLIENT_SECRET: "${OAUTH_GITHUB_CLIENT_SECRET}"
      OAUTH_GITHUB_REDIRECT_URL: "${OAUTH_GITHUB_REDIRECT_URL:-http://localhost:8080/api/auth/oauth/github/callback}"
      COOKIE_SAMESITE: "${COOKIE_SAMESITE:-lax}"
      COOKIE_SECURE: "${COOKIE_SECURE:-false}"
      SESSION_COOKIE_NAME: "${SESSION_COOKIE_NAME:-trellolite_sess}"
      SESSION_TTL: "${SESSION_TTL:-336h}"
    volumes:
      - ./web:/app/web:ro

volumes:
  dbdata:
