services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: trellolite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
      - DATABASE_URL=postgres://postgres:postgres@db:5432/trellolite?sslmode=disable
    volumes:
      - ./web:/app/web:ro

volumes:
  dbdata:
